import tkinter as tk
from tkinter import *
from tkinter import ttk
from PIL import Image 
##from PIL import ImageTk
##este es el ejemplo 2
print("Hola chaval")
print("eyeyeyeyeyey")
print("jejejejje")
ventana = tk.Tk()
print("Al abisaid le gusta la lizania")
id = StringVar()
correo= StringVar()
nombre_p=StringVar()
desc=StringVar()   
matricula = StringVar()
nombre = StringVar()
codigo= StringVar()
fecha= StringVar()
precio_u= float()
precio_p= float()
unidad_u= float()
unidad_p= float()
total_u= float()
total_p= float()
imagen= StringVar()
link=StringVar()
link.set("https://drive.google.com/file/d/1ujb4a8WLJhY-DUcav2t-5OxmG7qHeBWV/view?usp=drive_link")

titulo_label = Label(text="Registro de productos", bg="#171EE7", font=("Arial", 16))
titulo_label.pack(fill=tk.X)    

id_label= Label(text="Identificador del producto:", bg="#FFEEDD")
id_label.place(x=3, y=60)
id_entry= Entry(textvariable=id, width="40")
id_entry.place(x=170, y=60)
matricula_label = Label(text="Matricula-Vendedor:", bg="#FFEEDD")
matricula_label.place(x=3, y=90)
matricula_entry = Entry(textvariable=matricula, width="40")
matricula_entry.place(x=170, y=90)
nombre_label = Label(text="Nombre Vendedor:", bg="#FFEEDD")
nombre_label.place(x=3, y=120)
nombre_entry = Entry(textvariable=nombre, width="40")
nombre_entry.place(x=170, y=120)
nombre_p_label = Label(text="Nombre del producto:", bg="#FFEEDD")
nombre_p_label.place(x=3, y=150)
nombre_p_entry = Entry(textvariable=nombre_p, width="40")
nombre_p_entry.place(x=170, y=150)
desc_label = Label(text="Descripcion del producto:", bg="#FFEEDD")
desc_label.place(x=3, y=180)
desc_entry = Entry(textvariable=desc, width="40")
desc_entry.place(x=170, y=180)
codigo_label = Label(text="Codigo del producto:", bg="#FFEEDD")
codigo_label.place(x=3, y=210)
codigo_entry = Entry(textvariable=codigo, width="40")
codigo_entry.place(x=170, y=210)
fecha_label = Label(text="Fecha actual:", bg="#FFEEDD")
fecha_label.place(x=3, y=240)
fecha_entry = Entry(textvariable=fecha, width="40")
fecha_entry.place(x=170, y=240)
precio_u_label = Label(text="Precio unitario:", bg="#FFEEDD")
precio_u_label.place(x=3, y=270)
precio_u_entry = Entry(textvariable=precio_u, width="40")
precio_u_entry.place(x=170, y=270)
precio_p_label = Label(text="Precio al publico:", bg="#FFEEDD")
precio_p_label.place(x=3, y=300)
precio_p_entry = Entry(textvariable=precio_p, width="40")
precio_p_entry.place(x=170, y=300)
unidad_u_label = Label(text="Unidades ventidas unitarias:", bg="#FFEEDD")
unidad_u_label.place(x=3, y=330)
unidad_u_entry = Entry(textvariable=unidad_u, width="40")
unidad_u_entry.place(x=170, y=330)
unidad_p_label = Label(text="Unidades vendidas al publico:", bg="#FFEEDD")
unidad_p_label.place(x=3, y=360)
unidad_p_entry = Entry(textvariable=unidad_p, width="40")
unidad_p_entry.place(x=170, y=360)
total_u_label = Label(text="Total ventas unitarias:", bg="#FFEEDD")
total_u_label.place(x=3, y=390)
total_u_entry = Entry(textvariable=total_u, width="40")
total_u_entry.place(x=170, y=390)
total_p_label = Label(text="Total ventas al publico:", bg="#FFEEDD")
total_p_label.place(x=3, y=420)
total_p_entry = Entry(textvariable=total_p, width="40")
total_p_entry.place(x=170, y=420)

#el archivo puede no abrir por la ruta ya que al estar en el drive la ruta puede ser diferente a cuando esta en mi computadora
imagen = Image.open("Ingenieria en software II//Avance 3 para primer parcial Abisaid Gpe Angulo Munguia//29-24040115.png")
imagen_redimensionada = imagen.resize((300, 300))  
imagen_red = ImageTk.PhotoImage(imagen_redimensionada)

label_imagen = Label(ventana, image=imagen_red)
label_imagen.place(x=500, y=75)

link_label = Label(text="Link del producto:", bg="#FFEEDD")
link_label.place(x=500, y=380)
link_entry = Entry(textvariable=link, width="40") 
link_entry.place(x=600, y=380)
imagen_desc_label = Label(text="Imagen del producto:", bg="#FFEEDD")
imagen_desc_label.place(x=500, y=50)

boton_guardar = Button(text="Guardar", bg="#17DE1D")
boton_guardar.place(x=100, y=450, width=78)   
boton_consultar = Button(text="Consultar", bg="#137AE1")
boton_consultar.place(x=180, y=450, width=78)
boton_borrar = Button(text="Borrar", bg="#E11313")
boton_borrar.place(x=260, y=450, width=78)
boton_tomar=Button(text="Tomar foto", bg="#E1A213")
boton_tomar.place(x=340, y=450, width=78)
boton_web=Button(text="Visitar sitio Web", bg="#13E1C5")
boton_web.place(x=100, y=475, width=318)

ventana.title("Abisaid Guadalupe Angulo Munguia 24040115")
ventana.geometry("850x500")
ventana.mainloop()